### ISSUE TITLE
Titan earn rewards can be stacked

### ISSUE THREAD

**Issue by cpdt** [R2Northstar/NorthstarMods#256]
This has been reported to me a few times although I've never noticed it - the earnmeter stacks titan rewards so you can die in your titan and respawn with another one ready.

**Comment by ASpoonPlaysGames** [comment]
Thats... weird. I haven't noticed this either personally.

Potentially it's some auto-titan based weirdness? Like you can gain meter when your auto titan is out or something idk.

I'll do some testing this evening and try figure it out

**Comment by BobTheBob9** [comment]
i've had this reported a few times but i've yet to be able to reproduce, i've heard ejecting/dying while using your core can cause it though

**Comment by Dinorush** [comment]
I just tried testing each with 50%/full core meter:
- Ejecting with X core meter
- Dying with X core meter
- Having auto titan die with X core meter
- Having auto titan die after trying to get a full meter with it alive

I also tried ejecting and dying while core was active. None of these worked to reproduce the bug.

Although, if this bug is with latest release Northstar, it's likely that #212 already fixes this since it is much more liberal with resetting the earn meter. (I did also test these cases with #212 active and did not reproduce the bug)

**Comment by P0pMan20** [comment]
I've been able to reproduce this bug a couple of times now. It seems that using your titan core and then dying triggers it, but the 'Core Name' text must be on the death screen too?

I managed to get the bug on video 
[https://youtu.be/4wC6Cdchs1U](https://youtu.be/4wC6Cdchs1U)

**Comment by ASpoonPlaysGames** [comment]
So like dying with core active maybe? Hmm

**Comment by Dinorush** [comment]
No, the core is not active during death in the clip. I'll try looking into it again

**Comment by Zanieon** [comment]
Seems like this issue actually doesn't happen anymore as Dinorush mentioned the fix at #212
