### ISSUE TITLE
Disconnected: Authentication Failed

### ISSUE THREAD

**Issue by WingsOfCoronia** [R2Northstar/NorthstarMods#272]
Is the Northstar Client down since yesterday or something? I keep getting this "Authentication Failed" problem...

**Comment by SamLam140330** [comment]
Yes, we need to took down the master server to investigate a few security vulnerabilities because of an exploit in the vanilla game https://github.com/R2Northstar/Northstar/issues/124#issuecomment-1073206536
For more info, you can join the official Discord server: https://discord.gg/northstar
When the server is back online, we will announce it on the Discord server

**Comment by WingsOfCoronia** [comment]
That's boring as hell...
Thanks though
