### ISSUE TITLE
Some random northstar specific translations dont load polish translations

### ISSUE THREAD

**Issue by eve-v0** [R2Northstar/NorthstarMods#845]
![image](https://github.com/user-attachments/assets/22a278a1-fe1d-4199-b3f6-da211299a2cb)
<img width="269" alt="image" src="https://github.com/user-attachments/assets/3b82f1b8-dc8d-4a7f-94b8-31d9184362ed">
<img width="253" alt="image" src="https://github.com/user-attachments/assets/82f598f2-3557-4734-8297-924280e86440">
<img width="377" alt="image" src="https://github.com/user-attachments/assets/bdb70905-0610-4641-9290-92cfde34fc03">

I double checked localisation file and it seems that it isnt the problem
<img width="227" alt="image" src="https://github.com/user-attachments/assets/f2da9af1-a5f0-455b-84f3-e9fd07236f0f">
<img width="222" alt="image" src="https://github.com/user-attachments/assets/87d55850-5271-4e18-bf63-f263b09bfcc5">
<img width="311" alt="image" src="https://github.com/user-attachments/assets/1e9d3eab-9180-4adf-af35-db6ed563e00d">

**Comment by ASpoonPlaysGames** [comment]
I reckon the issue is with https://github.com/R2Northstar/NorthstarMods/blob/a1e77030f834219a12252925dd9204f00b74e30d/Northstar.Client/mod/resource/northstar_client_localisation_polish.txt#L17 the `"` need to be escaped I think (currently this would cause the file parsing to be all messed up for anything past this point)
