### ISSUE TITLE
All gamemodes in private match are marked as locked

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarMods#878]
![image](https://github.com/user-attachments/assets/f48758b0-a00b-4ffe-a383-736e1f552dd2)

Bug introduced in #624 (I failed to catch it in testing cause I was tired, sorry)

**Comment by NachosChipeados** [comment]
It seems like it happens because of this section in ``menu_mode_select.nut``
![Screenshot 2024-09-11 105153](https://github.com/user-attachments/assets/dc821480-ed7f-44f8-b86f-27f488847013)

Disabling it fixes it
![Screenshot 2024-09-11 105303](https://github.com/user-attachments/assets/cfbe2710-31bb-45f7-9f18-7a635f5b1f12)

**Comment by NachosChipeados** [comment]
Oh right yeah, i missed that
